#!/usr/bin/env node
/**
 * Taste Handoff — create a compact benchmark/review package without dependencies.
 * Run from the user project root:
 *   node <skill-root>/scripts/taste-handoff.mjs [project-root] [out-dir]
 */
import fs from 'node:fs';
import path from 'node:path';

const projectRoot = path.resolve(process.argv[2] || process.cwd());
const outDir = path.resolve(projectRoot, process.argv[3] || 'taste-benchmark-return');
const projectOut = path.join(outDir, 'project');
const evidenceOut = path.join(outDir, 'evidence');

const denyDirs = new Set(['node_modules','dist','build','.git','.next','.nuxt','.cache','.vite','coverage','taste-benchmark-return']);
const allowRootFiles = [
  'package.json','package-lock.json','pnpm-lock.yaml','yarn.lock','bun.lockb',
  'index.html','vite.config.js','vite.config.ts','vite.config.mjs','next.config.js','next.config.mjs',
  'tailwind.config.js','tailwind.config.ts','postcss.config.js','tsconfig.json','jsconfig.json'
];
const allowDirs = ['src','public','app','pages','components','styles'];

function copyRecursive(src,dst){
  if(!fs.existsSync(src)) return;
  const st=fs.statSync(src);
  if(st.isDirectory()){
    if(denyDirs.has(path.basename(src))) return;
    fs.mkdirSync(dst,{recursive:true});
    for(const name of fs.readdirSync(src)) copyRecursive(path.join(src,name),path.join(dst,name));
  } else {
    fs.mkdirSync(path.dirname(dst),{recursive:true});
    fs.copyFileSync(src,dst);
  }
}

fs.rmSync(outDir,{recursive:true,force:true});
fs.mkdirSync(projectOut,{recursive:true});
fs.mkdirSync(evidenceOut,{recursive:true});

for(const f of allowRootFiles){
  const src=path.join(projectRoot,f); if(fs.existsSync(src)) copyRecursive(src,path.join(projectOut,f));
}
for(const d of allowDirs){
  const src=path.join(projectRoot,d); if(fs.existsSync(src)) copyRecursive(src,path.join(projectOut,d));
}

const taste=path.join(projectRoot,'.taste');
if(fs.existsSync(taste)) copyRecursive(taste,path.join(evidenceOut,'.taste'));

// Copy common benchmark screenshots/reports if they live outside .taste.
for(const d of ['screenshots','qa','evidence']){
  const src=path.join(projectRoot,d); if(fs.existsSync(src)) copyRecursive(src,path.join(evidenceOut,d));
}
for(const f of ['RUN_SUMMARY.md','README.md']){
  const src=path.join(projectRoot,f); if(fs.existsSync(src)) copyRecursive(src,path.join(outDir,f));
}

const manifest={
  tool:'Taste Handoff',version:'1.0.0',generatedAt:new Date().toISOString(),projectRoot,
  excluded:[...denyDirs],
  contents:[]
};
function walk(dir){
  if(!fs.existsSync(dir)) return;
  for(const e of fs.readdirSync(dir,{withFileTypes:true})){
    const full=path.join(dir,e.name);
    if(e.isDirectory()) walk(full);
    else manifest.contents.push(path.relative(outDir,full).replaceAll('\\','/'));
  }
}
walk(outDir);
fs.writeFileSync(path.join(outDir,'handoff-manifest.json'),JSON.stringify(manifest,null,2));
if(!fs.existsSync(path.join(outDir,'README.md'))){
  fs.writeFileSync(path.join(outDir,'README.md'),`# Taste Benchmark Return\n\nCompact source and evidence package generated by taste-handoff.mjs.\n\nExcluded dependency/build/cache directories by design.\n`);
}
console.log(`Taste Handoff: PASS — ${outDir}`);
console.log(`Files: ${manifest.contents.length}`);
